iecquest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import quests.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quests/', views.quests),
    path('quests/<slug:slug>', views.quest_detail, name='quest_detail'),
    path('quests/<slug:slug>/<slug:model_slug>', views.model_detail, name='model_detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quests/models.py
from django.db import models
from django.conf import settings


class Quest(models.Model):
    start_time = models.DateTimeField('start_time', auto_now=False)
    end_time = models.DateTimeField('end_time')
    slug = models.SlugField()
    title = models.CharField(max_length=50)

class ModelVisual(models.Model):
    model = models.FileField(upload_to='media', null=True, blank=True)
    url = models.URLField(max_length=500)
    slug = models.SlugField()
    scales=models.CharField(max_length=50, default='1 1 1')
    rotation=models.CharField(max_length=50, default='0 0 0')
    position=models.CharField(max_length=50, default='0 0 0')
    quest = models.ForeignKey(Quest, verbose_name="quest", on_delete=models.CASCADE)

quests/views.py
from django.shortcuts import render

from .models import Quest, ModelVisual

# Create your views here.
def quests(request):
    quests = Quest.objects.all()
    return render(request, 'quests.html', { 'quests': quests })

def quest_detail(request, slug):
    quest = Quest.objects.get(slug=slug)
    return render(request, 'quest.html', { 'quest': quest })

def model_detail(request, slug, model_slug):
    model = ModelVisual.objects.get(slug=model_slug)
    return render(request, 'model.html', { 'model': model })

quests/templates/model.html
<html>

<head>
	<title>Parcel Sandbox</title>
	<meta charset="UTF-8" />
	<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
	<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js">
	
	</script>
</head>

<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>
        <a-assets>
            <a-asset-item id="model" src="{{model.url}}">
        </a-assets>

		<a-marker preset="hiro">
            <a-obj-model src="#model" scale="{{model.scales}}" rotation="{{model.rotation}}" position="{{model.position}}" ></a-obj-model>

        </a-marker>
		<a-entity camera></a-entity>
	</a-scene>
</body>

</html>

quests/templates/quest.html
{{quest.title}}

<ul>
{% for model in quest.modelvisual_set.all %}
    <li><a href="{% url 'model_detail' quest.slug model.slug %}">{{ model.slug }}</a></li>
{% endfor %}
</ul>

quests/templates/quests.html
<ul>
{% for quest in quests %}
    <li><a href="{% url 'quest_detail' quest.slug %}">{{ quest.title }}</a></li>
{% endfor %}
</ul>